services:
  js-app:
    build: ./frontend
    container_name: "myweb"
    ports:
      - '8020:8020'
      # - "3000:3000"
    volumes:
      - .:/src
    tty: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true